module.exports = {
  base: '/js/',
  title: `You Don't Know JS （中文版）`,
  description: `《You Don't Know JS 》（中文版）`,
  themeConfig: {
    lastUpdated: 'Last Updated',
    smoothScroll: true,
    nav: [
      { text: 'Github', link: 'https://github.com/getify/You-Dont-Know-JS/tree/1ed-zh-CN' },
      {
        text: '推荐阅读',
        items: [
          { text: '《ECMAScript 6 入门》', link: 'https://roojay.com/es6tutorial/' },
          { text: '《TypeScript Handbook》（中文版）', link: 'https://roojay.com/typescript/' },
        ],
      },
    ],
    sidebar: [
      ['/up & going/foreword.md', '序'],
      ['/preface.md', '前言'],
      ['/up & going/apA.md', '鸣谢'],
      {
        title: '入门与进阶',
        path: '/up & going',
        collapsable: false,
        sidebarDepth: 1,
        children: [
          ['/up & going/ch1.md', '第一章：进入编程'],
          ['/up & going/ch2.md', '第二章：进入JavaScript'],
          ['/up & going/ch3.md', '第三章：进入YDKJS'],
        ],
      },
      {
        title: '作用域与闭包',
        path: '/scope & closures',
        collapsable: false,
        sidebarDepth: 1,
        children: [
          ['/scope & closures/ch1.md', '第一章：什么是作用域？'],
          ['/scope & closures/ch2.md', '第二章：词法作用域'],
          ['/scope & closures/ch3.md', '第三章：函数与块儿作用域'],
          ['/scope & closures/ch4.md', '第四章：提升'],
          ['/scope & closures/ch5.md', '第五章：作用域闭包'],
          ['/scope & closures/apA.md', '附录A：动态作用域'],
          ['/scope & closures/apB.md', '附录B：填补块儿作用域'],
          ['/scope & closures/apC.md', '附录C：词法 this'],
        ],
      },
      {
        title: 'this与对象原型',
        path: '/this & object prototypes',
        collapsable: false,
        sidebarDepth: 1,
        children: [
          ['/this & object prototypes/ch1.md', '第一章：this 是什么'],
          ['/this & object prototypes/ch2.md', '第二章：this 豁然开朗'],
          ['/this & object prototypes/ch3.md', '第三章：对象'],
          ['/this & object prototypes/ch4.md', '第四章：混合（淆）“类”的对象'],
          ['/this & object prototypes/ch5.md', '第五章：原型'],
          ['/this & object prototypes/ch6.md', '第六章：行为委托'],
          ['/this & object prototypes/apA.md', '附录A：ES6 class'],
        ],
      },
      {
        title: '类型与文法',
        path: '/types & grammar',
        collapsable: false,
        sidebarDepth: 1,
        children: [
          ['/types & grammar/ch1.md', '第一章：类型'],
          ['/types & grammar/ch2.md', '第二章：值'],
          ['/types & grammar/ch3.md', '第三章：原生类型'],
          ['/types & grammar/ch4.md', '第四章：强制转换'],
          ['/types & grammar/ch5.md', '第五章：文法'],
          ['/types & grammar/apA.md', '附录A：与环境混合的 JavaScript'],
        ],
      },
      {
        title: '异步与性能',
        path: '/async & performance',
        collapsable: false,
        sidebarDepth: 1,
        children: [
          ['/async & performance/ch1.md', '第一章: 异步:现在与稍后'],
          ['/async & performance/ch2.md', '第二章：回调'],
          ['/async & performance/ch3.md', '第三章：Promise'],
          ['/async & performance/ch4.md', '第四章：Generator'],
          ['/async & performance/ch5.md', '第五章：程序性能'],
          ['/async & performance/ch6.md', '第六章：基准分析与调优'],
          ['/async & performance/apA.md', '附录A：库：asynquence'],
          ['/async & performance/apB.md', '附录B：高级异步模式'],
        ],
      },
      {
        title: 'ES6与未来',
        path: '/es6 & beyond',
        collapsable: false,
        sidebarDepth: 1,
        children: [
          ['/es6 & beyond/ch1.md', '第一章：ES？现在与未来'],
          ['/es6 & beyond/ch2.md', '第二章：语法'],
          ['/es6 & beyond/ch3.md', '第三章：组织'],
          ['/es6 & beyond/ch4.md', '第四章：异步流程控制'],
          ['/es6 & beyond/ch5.md', '第五章：集合'],
          ['/es6 & beyond/ch6.md', '第六章：新增 API'],
          ['/es6 & beyond/ch7.md', '第七章：元编程'],
          ['/es6 & beyond/ch8.md', '第八章：ES6 之后'],
        ],
      },
    ],
  },
};
